Rename settings command
Rename the settings command, so that it does conflict Sinatra's built-in settings variable when running methods defined in the Sinatra app from tux. (i.e. if I set a variable in a config block, like so, 

configure do 
...
set :cache_time, 86400 #24 hours in seconds
...
end 

then use it in a method:

def get_price(style_id, zip = '80202')
  APICache.get("typically equipped used tmv for #{style_id} in #{zip}", cache: settings.cache_time, period: 0, fail: Null.new) do 
...

I get the output of the tux settings command, then the following error when trying to run the method from within tux: 
NoMethodError: undefined method `cache_time' for nil:NilClass